import CONFIG from '../../config';

const API_ENDPOINT = {
  LIST_RESTAURANTS: `${CONFIG.API_BASE_URL}list`,
  DETAIL_RESTAURANT: `${CONFIG.API_BASE_URL}detail/`,
  POST_REVIEW_ON_RESTAURANT: `${CONFIG.API_BASE_URL}review`,
};

export default API_ENDPOINT;
